name: Test Murkit Feed

on:
  workflow_dispatch:

jobs:
  test-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm install

      - name: Run Murkit script
        run: node murkit.js
